### ISSUE TITLE
Feature request: settings for toggling animation

### ISSUE THREAD

**Issue by nashidk** [mrozio13pl/sudoku-in-terminal#1]
Please add a settings to turn off the animation, and if possible make the 'o' equivalent to enter

**Comment by mrozio13pl** [comment]
Sure, but why should `o` have the same effect as `Enter`? I can't really see a real use case.

**Comment by nashidk** [comment]
`o` stands for open in many terminal applications like vim and yazi, so most users used vim tend to use `o` , but it's optional
